name: Ayush Patwari, Graduate Student

# Variables set by GitHub
safe: true
lsi: false
highlighter: rouge
source: .

# Use nice sensible URLs like:
#
#    /nice/sensible/url
#
# Not:
#
#    /15/05/12/nasty/url
#
permalink: /posts/:title

# Enable HTTP redirects
gems:
  - jekyll-redirect-from

# Ignore patterns
exclude: [README.md, template/]
